// pokedex-react/src/components/PokeFooter.tsx

export const PokeFooter = () => {
  return (
    <footer aria-labelledby="footer-heading" className="bg-poke-primary-700 sticky bottom-0 left-0 z-10 right-0">
      <h2 id="footer-heading" className="sr-only">
        Footer
      </h2>
      <div className="mx-auto max-w-7xl px-6 pb-8 lg:px-8">
        <div className="border-t border-white/10 mt-8">
          <p className="text-xs leading-5 text-gray-400">&copy; 2024 Your Company, Inc. All rights reserved.</p>
        </div>
      </div>
    </footer>
  )
}

// pokedex-svelte/src/components/PokeFooter.svelte
<footer
  aria-labelledby="footer-heading"
  class="bg-poke-primary-700 fixed bottom-0 left-0 z-10 right-0"
>
  <h2 id="footer-heading" class="sr-only">Footer</h2>
  <div class="mx-auto max-w-7xl px-6 pb-8 lg:px-8">
    <div class="border-t border-white/10 mt-8">
      <p class="text-xs leading-5 text-gray-400">
        &copy; 2024 Your Company, Inc. All rights reserved.
      </p>
    </div>
  </div>
</footer>
