// frameworks/pokedex-svelte-v1/src/routes/pokedex/+page.svelte
<script>
  import Card from "$lib/components/Card.svelte";
</script>

<Card href="/pokedex/tabletest" title="Tabella Pokemon" description="Go To Tabella" />
<Card href="/pokedex/foldertree" title="Folder Pokemon" description="Go To Folder" />
<Card href="/pokedex/foldertreestyle" title="Folder Style Pokemon" description="Go To Folder Style" />
<!-- <Card href="/pokedex/fiftyanimations" title="Animazioni Pokemon" description="Go To Animations" /> -->
<!-- <Card href="/pokedex/realtimes" title="RealTime Pokemon" description="Go To Real Time" /> -->
<Card href="/pokedex/classcomposition" title="Class Composition Pokemon" description="Go To Class Composition" />

// frameworks/pokedex-next-v1/app/pokedex/page.tsx
import Card from '@/components/Card';

export default function App() {
  return (
    <>
      <Card href="/pokedex/tabletest" title="Tabella Pokemon" description="Go To Tabella" />
      <Card href="/pokedex/foldertree" title="Folder Pokemon" description="Go To Folder" />
      <Card href="/pokedex/foldertreestyle" title="Folder Style Pokemon" description="Go To Folder Style" />
      {/* <Card href="/pokedex/fiftyanimations" title="Animazioni Pokemon" description="Go To Animations" /> */}
      {/* <Card href="/pokedex/realtimes" title="RealTime Pokemon" description="Go To Real Time" /> */}
      <Card href="/pokedex/classcomposition" title="Class Composition Pokemon" description="Go To Class Composition" />
    </>
  );
}
