// dev-talk/table-test-svelte/src/TableFullActions.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { generateTestData } from "./table-sandbox";
  import type { TableRow } from "./type.table-sandbox";

  const { cols = 1000, rows = 10 } = $props();

  let tableData: TableRow[] = $state([]);
  const ROW_COUNT = cols;
  const COL_COUNT = rows;

  function createRows() {
    console.time("Svelte Rendering Time");

    tableData = generateTestData(ROW_COUNT, COL_COUNT);
    setTimeout(() => {
      console.timeEnd("Svelte Rendering Time");
    }, 0);
  }

  function clearRows() {
    tableData = [];
  }

  function swapRowsWithCloneArray(): void {
    console.time("Svelte Swap Time");

    if (tableData.length < 20) {
      setTimeout(() => {
        console.timeEnd("Svelte Swap Time");
      }, 0);
      return;
    }

    const newData = [...tableData]; // Crea una copia per l'immutabilità
    for (let i = 0; i < 10; i++) {
      const endIndex = newData.length - 1 - i;
      // Scambia il primo con l'ultimo, il secondo con il penultimo, etc.
      const temp = newData[i];
      newData[i] = newData[endIndex];
      newData[endIndex] = temp;
    }
    tableData = newData; // Restituisce il nuovo stato per aggiornare il segnale
     
    setTimeout(() => {
      console.timeEnd("Svelte Swap Time");
    }, 0);
  }

  function swapRows(): void {
    console.time("Svelte Swap Time");
    for (let i = 0; i < 10; i++) {
      const endIndex = tableData.length - 1 - i;
      const temp = tableData[i];
      tableData[i] = tableData[endIndex];
      tableData[endIndex] = temp;
    }
    setTimeout(() => {
      console.timeEnd("Svelte Swap Time");
    }, 0);
  }

  // Calcoliamo le intestazioni solo una volta se ci sono dati
  let colHeaders: string[] = $derived(
    tableData.length > 0
      ? Array.from({ length: COL_COUNT }, (_, i) => `Campo ${i + 1}`)
      : []
  );
  let colIndexes = $derived(Array.from({ length: COL_COUNT }, (_, i) => i));


</script>

<div class="p-8 font-sans">
  <h1 class="text-2xl font-bold mb-4">
    Svelte 5 Performance Test (TypeScript)
  </h1>
  <p class="mb-4">
    Test per creare una tabella con {ROW_COUNT} righe e {COL_COUNT} colonne.
  </p>
  <div class="flex space-x-2 mb-4">
    <button
     id="create"
      onclick={createRows}
      class="px-4 py-2 bg-orange-600 text-white rounded hover:bg-orange-700 focus:outline-none focus:ring-2 focus:ring-orange-500"
    >
      Crea {ROW_COUNT} Righe
    </button>
    <button
      onclick={clearRows}
      class="px-4 py-2 bg-gray-400 text-white rounded hover:bg-gray-500 focus:outline-none focus:ring-2 focus:ring-gray-300"
    >
      Pulisci Tabella
    </button>
    <button
      id="swap"
      onclick={swapRowsWithCloneArray}
      class="px-4 py-2 bg-gray-400 text-white rounded hover:bg-gray-500 focus:outline-none focus:ring-2 focus:ring-gray-300"
    >Swap</button>
    <button
      id="swapCloneArray"
      onclick={swapRowsWithCloneArray}
      class="px-4 py-2 bg-gray-400 text-white rounded hover:bg-gray-500 focus:outline-none focus:ring-2 focus:ring-gray-300"
    >
      CloneArray
    </button>
  </div> 

  <div class="overflow-x-auto border border-gray-200 rounded-lg">
    <table class="min-w-full divide-y divide-gray-200">
      <thead class="bg-gray-50">
        <tr>
          <th
            class="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
            >ID</th
          >
          {#if tableData.length > 0}
            {#each colHeaders as header}
              <th
                class="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
              >
                {header}
              </th>
            {/each}
          {/if}
        </tr>
      </thead>
      <tbody class="bg-white divide-y divide-gray-200">
        {#each tableData as row (row.id)}
          <tr>
            <td
              class="px-4 py-2 whitespace-nowrap text-sm font-medium text-gray-900"
              >{row.id + 1}</td
            >
            {#each colIndexes as i}
              <td class="px-4 py-2 whitespace-nowrap text-sm text-gray-700">
                {row["field" + i]}
              </td>
            {/each}
          </tr>
        {/each}
      </tbody>
    </table>
  </div>
</div>

// dev-talk/table-test-angular-zoneless/src/app/table-full-actions/table-full-actions.ts
import {
  Component,
  computed,
  Input,
  signal,
} from '@angular/core';

import { generateTestData } from '../utils/table-sandbox';
import { TableRow } from '../utils/type.table-sandbox';

@Component({
  selector: 'app-table-full-actions',
  imports: [],
  templateUrl: './table-full-actions.html',
  styleUrl: './table-full-actions.css'
})
export class TableFullActions {
  @Input() cols: number = 20;
  @Input() rows: number = 1000;

  public tableData = signal<TableRow[]>([]);

  public colHeaders = computed(() => {
    return this.tableData().length > 0
      ? Array.from({ length: this.cols }, (_, i) => `Campo ${i + 1}`)
      : [];
  });

  createRows(): void {    
    
    console.time("Angular-Zoneless Rendering Time");
    const data = generateTestData(this.rows, this.cols);
    this.tableData.set(data);
    setTimeout(() => {
      console.timeEnd("Angular-Zoneless Rendering Time");
    }, 0);
  }

  clearRows(): void {
    this.tableData.set([]);
  }

  swapRows(): void {
        console.time("Angular-Zoneless Swap Time");

    this.tableData.update(currentData => {
      if (currentData.length < 20) {
        return currentData; // Non ci sono abbastanza righe, restituisce lo stato corrente
      }

      const newData = [...this.tableData()]; // Crea una copia per l'immutabilità
      for (let i = 0; i < 10; i++) {
        const endIndex = newData.length - 1 - i;
        // Scambia il primo con l'ultimo, il secondo con il penultimo, etc.
        const temp = newData[i];
        newData[i] = newData[endIndex];
        newData[endIndex] = temp;
      }
      return newData; // Restituisce il nuovo stato per aggiornare il segnale
    });
      setTimeout(() => {
        console.timeEnd("Angular-Zoneless Swap Time");
    }, 0);
  }
}
