// frameworks/pokedex-svelte-v1/src/routes/app/+page.svelte
<script>
  import Card from "$lib/components/Card.svelte";
</script>

<Card href="/app/tabletest" title="Tabella Pokemon" description="Go To Tabella" />
<Card href="/app/foldertree" title="Folder Pokemon" description="Go To Folder" />
<Card href="/app/fiftyanimations" title="Animazioni Pokemon" description="Go To Animations" />
<Card href="/app/realtimes" title="RealTime Pokemon" description="Go To Real Time" />
<Card href="/app/kpistats" title="Statistiche Pokemon" description="Go To Statistiche" />

// frameworks/pokedex-next-v1/app/app/page.tsx
import Card from '@/components/Card';

export default function App() {
  return (
    <>
      <Card href="/app/tabletest" title="Tabella Pokemon" description="Go To Tabella" />
      <Card href="/app/foldertree" title="Folder Pokemon" description="Go To Folder" />
      <Card href="/app/fiftyanimations" title="Animazioni Pokemon" description="Go To Animations" />
      <Card href="/app/realtimes" title="RealTime Pokemon" description="Go To Real Time" />
      <Card href="/app/kpistats" title="Statistiche Pokemon" description="Go To Statistiche" />
    </>
  );
}
